language: node_js
node_js:
- node
services:
- mongodb
before_deploy:
- npm run build
deploy:
  provider: npm
  email: anthony.kerz@gmail.com
  api_key:
    secure: BUupWernhe5531/dTCgjtGg2e6wuDtDgGlnDq6A+G62HWIPVkHBn/cAunIYkx2B+X6KAUbkhsvLZ2wrLYVFRFZjzvOvaim8gf0Z7IzsderifVDN29AWUhp7flnrbIlN5hEiROAM7VQVXjtoWjPAl85/IvmOSAbk5ZJrOuT/Vpx2S+Coo7vlxOeaEDWGAvhDrjFTOeNR8EWulEFv5fh3zyE4xPZ46mQedtz3wiQvhRoW6Zq8iNKH6P5b83UUKYi7TJ9RPsk3616X+k0OtWs7YchOrxaci9NI4CHacsfYrMbfmXEBryLJv9QW/BpXjHVdVym2RFeUOvu99zdaZvKu09mlQhMZt6D+iXAdCxw3/YUM+fZfEMV/WMcWz9h6N6agNmXV16ZHKgQwbVsB+bCLMcOYlEenhIqg7vTfLKRtrNq4RszIKsg1pe0+QXaP2QZ2kfMaquoz90kidhH+XZo+KCXkjOlnazOCaBz0grySybFtbEQAfeTjICdSyDQPPu8fF+CKHBpexn650nb2yUc8nuTFIdapSJHW11ZvgZPv6EiQRYu/6+5YSVFCb/QvSTmLn1py/WXk3G+HO42W4VP7MlW4RTWGFNO4OPndapK0z12uE9gdcXEp4IEoUG0DPCieRD2xMktQeLkNzmgD0+O3e64tzcTOlBizMIfTqN0YAxu4=
  skip_cleanup: true
  on:
    branch: master
    condition: "-z $TRAVIS_TAG"
